;(function(){var dfltPluginCfg={};var dfltGlobalCfg={"site":608326,"log":"","logSSL":"","domain":"ati-host.net","collectDomain":"logw320.ati-host.net","collectDomainSSL":"logws1320.ati-host.net","userIdOrigin":"server","pixelPath":"/hit.xiti","disableCookie":false,"disableStorage":false,"cookieSecure":false,"cookieDomain":".tongfangbms.com","preview":false,"plgs":["Campaigns","Clicks","ClientSideUserId","ContextVariables","Page","IdentifiedVisitor","InternalSearch","OnSiteAds"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":true,"base64Storage":false,"sendHitWhenOptOut":true,"forceHttp":false,"requestMethod":"GET","maxHitSize":2000};(function(a){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
var Utils=function(){function a(b){var e=typeof b;if("object"!==e||null===b)return"string"===e&&(b='"'+b+'"'),String(b);var c,f,l=[],d=b.constructor===Array;for(c in b)b.hasOwnProperty(c)&&(f=b[c],e=typeof f,"function"!==e&&"undefined"!==e&&("string"===e?f='"'+f.replace(/[^\\]"/g,'\\"')+'"':"object"===e&&null!==f&&(f=a(f)),l.push((d?"":'"'+c+'":')+String(f))));return(d?"[":"{")+String(l)+(d?"]":"}")}function h(a){return null===a?"":(a+"").replace(c,"")}function g(a){var e,c=null;return(a=h(a+""))&&
!h(a.replace(b,function(a,b,k,d){e&&b&&(c=0);if(0===c)return a;e=k||b;c+=!d-!k;return""}))?Function("return "+a)():null}var d=this,b=/(,)|(\[|{)|(}|])|"(?:[^"\\\r\n]|\\["\\\/bfnrt]|\\u[\da-fA-F]{4})*"\s*:?|true|false|null|-?(?!0\d)\d+(?:\.\d+|)(?:[eE][+-]?\d+|)/g,c=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g");d.isLocalStorageAvailable=function(){try{var a=localStorage;a.setItem("__storage_test__","__storage_test__");a.removeItem("__storage_test__");return!0}catch(e){return!1}};
d.isBeaconMethodAvailable=function(){return window.navigator&&"function"===typeof window.navigator.sendBeacon};d.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var e="",b,c,l,r,p,n,q=0;for(a=d.Base64._utf8_encode(a);q<a.length;)b=a.charCodeAt(q++),c=a.charCodeAt(q++),l=a.charCodeAt(q++),r=b>>2,b=(b&3)<<4|c>>4,p=(c&15)<<2|l>>6,n=l&63,isNaN(c)?p=n=64:isNaN(l)&&(n=64),e=e+this._keyStr.charAt(r)+this._keyStr.charAt(b)+this._keyStr.charAt(p)+this._keyStr.charAt(n);
return e},decode:function(a){var b="",c,f,l,r,p,n=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");n<a.length;)c=this._keyStr.indexOf(a.charAt(n++)),f=this._keyStr.indexOf(a.charAt(n++)),r=this._keyStr.indexOf(a.charAt(n++)),p=this._keyStr.indexOf(a.charAt(n++)),c=c<<2|f>>4,f=(f&15)<<4|r>>2,l=(r&3)<<6|p,b+=String.fromCharCode(c),64!=r&&(b+=String.fromCharCode(f)),64!=p&&(b+=String.fromCharCode(l));return b=d.Base64._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<
a.length;c++){var f=a.charCodeAt(c);128>f?b+=String.fromCharCode(f):(127<f&&2048>f?b+=String.fromCharCode(f>>6|192):(b+=String.fromCharCode(f>>12|224),b+=String.fromCharCode(f>>6&63|128)),b+=String.fromCharCode(f&63|128))}return b},_utf8_decode:function(a){for(var b="",c=0,f,d,r;c<a.length;)f=a.charCodeAt(c),128>f?(b+=String.fromCharCode(f),c++):191<f&&224>f?(d=a.charCodeAt(c+1),b+=String.fromCharCode((f&31)<<6|d&63),c+=2):(d=a.charCodeAt(c+1),r=a.charCodeAt(c+2),b+=String.fromCharCode((f&15)<<12|
(d&63)<<6|r&63),c+=3);return b}};d.loadScript=function(a,b){var c;b=b||function(){};c=document.createElement("script");c.type="text/javascript";c.src=a.url;c.async=!1;c.defer=!1;c.onload=c.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(c.readyState)&&(!document.documentMode||9>document.documentMode))c.onload=c.onreadystatechange=c.onerror=null,b(null,a)};c.onerror=function(a){c.onload=c.onreadystatechange=c.onerror=null;b({msg:"script not loaded",event:a})};
var f=document.head||document.getElementsByTagName("head")[0];f.insertBefore(c,f.lastChild)};d.cloneSimpleObject=function(a,b){if("object"!==typeof a||null===a||a instanceof Date)return a;var c=new a.constructor,f;for(f in a)a.hasOwnProperty(f)&&(void 0===f||b&&void 0===a[f]||(c[f]=d.cloneSimpleObject(a[f])));return c};d.isEmptyObject=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};d.isObject=function(a){return null!==a&&"object"===typeof a&&!(a instanceof Array)};d.ATVALUE="_ATVALUE";
d.ATPREFIX="_ATPREFIX";d.object2Flatten=function(a,b,c,f){var l={},r="",p="",n=[],q="",g=0,s;for(s in a)if(a.hasOwnProperty(s))if(l=d.splitProtocolAndKey(s),r=l.prefix||f||"",p=(b?b+"_":"")+l.key,d.isObject(a[s]))d.object2Flatten(a[s],p,c,r);else{n=p.split("_");q="";for(g=0;g<n.length;g++)l=d.splitProtocolAndKey(n[g]),r=l.prefix||r,q+=l.key+(g<n.length-1?"_":"");p=q||p;c[p]=c[p]||{};c[p][d.ATVALUE]=a[s];c[p][d.ATPREFIX]=r}};d.flatten2Object=function(a,b,c){b=b.split("_");var f,l;for(l=0;l<b.length-
1;l++)f=b[l],a[f]||(a[f]={}),a=a[f];if(a.hasOwnProperty(d.ATVALUE)){f=a[d.ATVALUE];var r=a[d.ATPREFIX];delete a[d.ATVALUE];delete a[d.ATPREFIX];a.$={};a.$[d.ATVALUE]=f;a.$[d.ATPREFIX]=r}c=d.cloneSimpleObject(c);a[b[l]]?a[b[l]].$=c:a[b[l]]=c};d.getFormattedObject=function(a){var b={},c,f;for(f in a)a.hasOwnProperty(f)&&(a[f].hasOwnProperty(d.ATVALUE)?(c=a[f][d.ATPREFIX]?a[f][d.ATPREFIX]+":"+f:f,b[c]=a[f][d.ATVALUE]):b[f]=d.getFormattedObject(a[f]));return b};d.completeFstLevelObj=function(a,b,c){if(a){if(b)for(var f in b)!b.hasOwnProperty(f)||
a[f]&&!c||(a[f]=b[f])}else a=b;return a};d.getObjectKeys=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b};d.objectToLowercase=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(d.isObject(a[c])?b[c.toLowerCase()]=d.objectToLowercase(a[c]):b[c.toLowerCase()]=a[c]);return b};d.splitProtocolAndKey=function(a){return 2>a.length||":"!==a[1]?{prefix:"",key:a.toLowerCase()}:4>a.length||":"!==a[3]?{prefix:a.substring(0,1).toLowerCase(),key:a.substring(2,a.length).toLowerCase()}:
{prefix:a.substring(0,3).toLowerCase(),key:a.substring(4,a.length).toLowerCase()}};d.jsonSerialize=function(b){try{return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(b):a(b)}catch(c){return null}};d.jsonParse=function(a){try{return"undefined"!==typeof JSON&&JSON.parse?JSON.parse(a+""):g(a)}catch(b){return null}};d.trim=function(a){try{return String.prototype.trim?a.trim():a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")}catch(b){return a}};d.arrayIndexOf=function(a,b){if(Array.prototype.indexOf){var c=
-1;"undefined"!==typeof a.indexOf(b)&&(c=a.indexOf(b));return c}return function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var e=0;1<arguments.length&&(e=Number(arguments[1]),e!=e?e=0:0!=e&&Infinity!=e&&-Infinity!=e&&(e=(0<e||-1)*Math.floor(Math.abs(e))));if(e>=c)return-1;for(e=0<=e?e:Math.max(c-Math.abs(e),0);e<c;e++)if(e in b&&b[e]===a)return e;return-1}.apply(a,[b])};d.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;return("x"===a?b:b&3|8).toString(16)})},num:function(a){var b=new Date,c=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:String(a)};return c(b.getHours())+""+c(b.getMinutes())+""+c(b.getSeconds())+""+function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};d.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};d.isPrerender=function(a){var b,c=!1,f=["webkit","ms"];if("prerender"===document.visibilityState)b=
"visibilitychange";else for(var l=0;l<f.length;l++)"prerender"===document[f[l]+"VisibilityState"]&&(b=f[l]+"visibilitychange");if("undefined"!==typeof b){var r=function(c){a(c);d.removeEvtListener(document,b,r)};d.addEvtListener(document,b,r);c=!0}return c};d.addEvtListener=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)};d.removeEvtListener=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,
c)};d.hashcode=function(a){var b=0;if(0===a.length)return b;for(var c=0;c<a.length;c++)var f=a.charCodeAt(c),b=(b<<5)-b+f,b=b|0;return b};d.setLocation=function(a){var b=a.location;a=window[a.target]||window;b&&(a.location.href=b)};d.dispatchCallbackEvent=function(a){var b;if("function"===typeof window.Event)b=new Event("ATCallbackEvent");else try{b=document.createEvent("Event"),b.initEvent&&b.initEvent("ATCallbackEvent",!0,!0)}catch(c){}b&&"function"===typeof document.dispatchEvent&&(b.name=a,document.dispatchEvent(b))};
d.addCallbackEvent=function(a){d.addEvtListener(document,"ATCallbackEvent",a)};d.removeCallbackEvent=function(a){d.removeEvent("ATCallbackEvent",a)};(function(){function a(b,c){c=c||{bubbles:!1,cancelable:!1,detail:void 0};var f;try{f=document.createEvent("CustomEvent"),f.initCustomEvent(b,c.bubbles,c.cancelable,c.detail)}catch(k){}return f}"function"===typeof window.CustomEvent?window.ATCustomEvent=window.CustomEvent:("function"===typeof window.Event&&(a.prototype=window.Event.prototype),window.ATCustomEvent=
a)})();d.addEvent=function(a,b,c,f){d[a]=new ATCustomEvent(a,{detail:{name:b,id:c}});d.addEvtListener(document,a,f)};d.removeEvent=function(a,b){d.removeEvtListener(document,a,b)};d.dispatchEvent=function(a,b){d[a]=d[a]||new ATCustomEvent(a,{detail:{name:b,id:-1}});try{document.dispatchEvent(d[a])}catch(c){}};d.privacy=new function(){this.CONSENTNO="Consent-NO"};d.optedOut=null;d.addOptOutEvent=function(a,b){d.addEvent("ATOptOutEvent","clientsideuserid",a,b)};d.removeOptOutEvent=function(a){d.removeEvent("ATOptOutEvent",
a)};d.dispatchOptOutEvent=function(a){d.optedOut=a;d.dispatchEvent("ATOptOutEvent","clientsideuserid")};d.userOptedOut=function(){d.dispatchOptOutEvent(!0)};d.userOptedIn=function(){d.dispatchOptOutEvent(!1)};d.isOptedOut=function(){if(null===d.optedOut){var a;a:{a=null;d.isLocalStorageAvailable()&&(a=localStorage.getItem("atuserid"));if(null===a){var b=/(?:^| )atuserid=([^;]+)/.exec(document.cookie);null!==b&&(a=b[1])}if(null!==a)try{a=decodeURIComponent(a)}catch(c){}if(a&&(a=d.jsonParse(a)||d.jsonParse(d.Base64.decode(a)),
null!==a)){a="OPT-OUT"===a.val;break a}a=!1}d.optedOut=a}return!!d.optedOut};d.consentReceived=function(a){d.consent=!!a};d.consent=!0;d.isTabOpeningAction=function(a){var b=!1;a&&(a.ctrlKey||a.shiftKey||a.metaKey||a.button&&1===a.button)&&(b=!0);return b}};ATInternet.Utils=new Utils;
var BuildManager=function(a){var h=this,g=0,d=0,b=["dz"],c="",k=function(a,b,c,e,f,d,k){a="&"+a+"=";return{param:a,paramSize:a.length,str:b,strSize:b.length,truncate:c,multihit:e,separator:f||"",encode:d,last:k}},e=function(a,b){var c="",e=0,f=0,d=0,e=-1,k=null,l=null,t;for(t in a)a.hasOwnProperty(t)&&(k=a[t])&&(e=b-f,k.last&&null!==l?l[t]=k:k.strSize+k.paramSize<=e?(c+=k.param+k.str,f+=k.paramSize+k.strSize):(l=l||{},l[t]=k,k.truncate&&(d=e-k.paramSize,k.separator&&(e=k.str.substring(0,e),e=k.encode?
e.lastIndexOf(encodeURIComponent(k.separator)):e.lastIndexOf(k.separator),0<e&&(d=e)),c+=k.param+k.str.substring(0,d),f+=k.paramSize+k.str.substring(0,d).length,l[t].str=k.str.substring(d,k.strSize),l[t].strSize=l[t].str.length)));return[c,l]},m=function(c,f,l){var r="",g=function(c){if(c==={})return[];var f=[],l;l={};var p=!1,n=void 0,q,m,g,h,s,w,u,y,C="",x;for(x in c)if(c.hasOwnProperty(x))if(w=s=h=g=!1,q=c[x]._value,m=c[x]._options||{},"boolean"===typeof m.encode&&(g=m.encode),"function"===typeof q&&
(q=q()),q=q instanceof Array?q.join(m.separator||","):"object"===typeof q?ATInternet.Utils.jsonSerialize(q):"undefined"===typeof q?"undefined":q.toString(),g&&(q=encodeURIComponent(q)),-1<ATInternet.Utils.arrayIndexOf(b,x)?h=!0:"boolean"===typeof m.truncate&&(h=m.truncate),"boolean"===typeof m.multihit&&(s=m.multihit),"boolean"===typeof m.last&&(w=m.last),q=k(x,q,h,s,m.separator,g,w),s)d-=q.paramSize+q.strSize,C+=q.param+q.str;else if(w)q.paramSize+q.strSize>d&&(q.str=q.str.substring(0,d-q.paramSize),
q.strSize=q.str.length),u=x,y=q;else if(l[x]=q,l[x].paramSize+l[x].strSize>d&&!l[x].truncate){a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:'Too long parameter: "'+l[x].param+'"',details:{value:l[x].str}});p=!0;n=x;break}u&&(l[u]=y);l=[l,p,n,C];c=l[0];p=l[1];r=l[3];p&&(l=l[2],c=c[l],c.str=c.str.substring(0,d-c.paramSize),c.strSize=c.str.length,p={},p.mherr=k("mherr","1",!1,!1,"",!1,!1),p[l]=c,c=p);c=e(c,d);if(null===c[1])f=c[0];else for(f.push(c[0]);null!==c[1];)c=e(c[1],d),f.push(c[0]);return f},
h="";a.buffer.presentInFilters(f,"hitType")||(f=a.buffer.addInFilters(f,"hitType",["page"]));f=a.buffer.addInFilters(f,"hitType",["all"]);var m;if(ATInternet.Utils.isObject(c)){f=a.buffer.addInFilters(f,"permanent",!0);f=a.buffer.get(f,!0);var w;for(m in c)c.hasOwnProperty(m)&&(w={},c[m]&&"object"===typeof c[m]&&c[m].hasOwnProperty("_value")?(h=c[m]._value,c[m].hasOwnProperty("_options")&&(w=c[m]._options)):h=c[m],f[m]={_value:h,_options:w});h=g(f)}else for(m in f=a.buffer.get(f,!0),h=g(f),f)f.hasOwnProperty(m)&&
(f[m]._options&&f[m]._options.permanent||a.buffer.del(m));l&&l(h,r)};h.getCollectDomain=function(){var b="",b=a.getConfig("logSSL")||a.getConfig("log"),c=a.getConfig("domain");return b=b&&c?b+"."+c:a.getConfig("collectDomainSSL")||a.getConfig("collectDomain")};var f=function(b){var c="",e=a.getConfig("baseURL");if(e)c=e;else{var e=h.getCollectDomain(),f=a.getConfig("pixelPath"),f=f||"/";"/"!==f.charAt(0)&&(f="/"+f);e&&(c=(a.getConfig("forceHttp")?"http://":"https://")+e+f)}e=a.getConfig("site");c&&
e?b&&b(null,c+"?s="+e):b&&b({message:"Config error"})},l=function(a,b,c){f(function(e,f){e?c&&c(e):(d=g-(f.length+27),m(a,b,function(a,b){var e=[],d=ATInternet.Utils.uuid().num(13);if(a instanceof Array)for(var k=1;k<=a.length;k++)e.push(f+b+"&mh="+k+"-"+a.length+"-"+d+a[k-1]);else e.push(f+b+a);c&&c(null,e)}))})},r=function(b,c,e,f,k,d){return function(){return function(l){a.emit(b,{lvl:k,details:{hit:c,method:e,event:l,isMultiHit:d}});f&&f()}}()};h.send=function(b,c,e,f){l(b,c,function(b,c){if(b)a.emit("Tracker:Hit:Build:Error",
{lvl:"ERROR",msg:b.message,details:{}}),e&&e();else for(var k=0;k<c.length;k++)h.sendUrl(c[k],e,f)})};g=Math.max(a.getConfig("maxHitSize")||0,2E3);d=Math.max(a.getConfig("maxHitSize")||0,2E3);c=a.getConfig("requestMethod");h.sendUrl=function(b,e,f){var k=-1<b.indexOf("&mh=");f=f||c;if(ATInternet.Utils.isOptedOut()&&!a.getConfig("sendHitWhenOptOut"))r("Tracker:Hit:Sent:NoTrack",b,f,e,"INFO",k)();else if("POST"===f&&ATInternet.Utils.isBeaconMethodAvailable()){f="Tracker:Hit:Sent:Error";var d="ERROR";
window.navigator.sendBeacon(b,null)&&(f="Tracker:Hit:Sent:Ok",d="INFO");r(f,b,"POST",e,d,k)()}else f=new Image,f.onload=r("Tracker:Hit:Sent:Ok",b,"GET",e,"INFO",k),f.onerror=r("Tracker:Hit:Sent:Error",b,"GET",e,"ERROR",k),f.src=b}},TriggersManager=function(){function a(a,c,k){for(var e=[],d=0;d<a.length;d++)a[d].callback(c,k),a[d].singleUse||e.push(a[d]);return e}function h(a,c,k,e){var d=a.shift();if("*"===d)return c["*"]=c["*"]||[],c["*"].push({callback:k,singleUse:e}),c["*"].length-1;if(0===a.length)return h([d,
"*"],c,k,e);c["*"]=c["*"]||[];c[d]=c[d]||{};return h(a,c[d],k,e)}function g(b,c,d,e){var m=c.shift();"*"!==m&&(0===c.length?g(b,[m,"*"],d,e):d[m]&&(d[m]["*"]=a(d[m]["*"],b,e),g(b,c,d[m],e)))}var d={};this.on=function(a,c,k){k=k||!1;return h(a.split(":"),d,c,k)};this.emit=function(b,c){d["*"]&&(d["*"]=a(d["*"],b,c));g(b,b.split(":"),d,c)}},PluginsManager=function(a){var h={},g={},d=0,b={},c=0,k=function(a){var b=!1;h[a]&&(b=!0);return b},e=this.unload=function(b){k(b)?(h[b]=void 0,a.emit("Tracker:Plugin:Unload:"+
b+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+b+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},m=this.load=function(b,c){"function"===typeof c?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(b)?(h[b]=new c(a),g[b]&&k(b)&&(g[b]=!1,d--,k(b+"_ll")&&e(b+"_ll"),0===d&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),a.emit("Tracker:Plugin:Load:"+b+":Ok",{lvl:"INFO"})):
a.emit("Tracker:Plugin:Load:"+b+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:c}});return a},f=this.isLazyloading=function(a){return a?!0===g[a]:0!==d},l=function(a){return!k(a)&&!f(a)&&k(a+"_ll")},r=function(b){g[b]=!0;d++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+b+".js"})},p=function(a){return l(a)?(r(a),!0):!1},n=function(a){b[a]?b[a]++:b[a]=1;c++},q=function(a,b,c,e){var f=
null;b=b.split(".");k(a)&&h[a][b[0]]&&(f=1<b.length&&h[a][b[0]][b[1]]?h[a][b[0]][b[1]].apply(h[a],c):h[a][b[0]].apply(h[a],c));e&&e(f)},v=function(e,f,d,k){n(e);a.onTrigger("Tracker:Plugin:Load:"+e+":Ok",function(){q(e,f,d,function(f){b[e]--;c--;0===c&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});k&&k(f)})},!0)},s=function(a){for(var b={mcount:0,plugins:{}},c=0;c<a.length;c++)h.hasOwnProperty(a[c])||(b.mcount++,b.plugins[a[c]]=!0);return b};
this.isExecWaitingLazyloading=function(){return 0!==c};a.exec=this.exec=function(a,b,c,e){l(a)?(v(a,b,c,e),r(a)):f(a)?v(a,b,c,e):q(a,b,c,e)};this.waitForDependencies=function(b,c){var e=s(b);if(0===e.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",{lvl:"INFO",details:{dependencies:b}}),c();else for(var f in e.plugins)e.plugins.hasOwnProperty(f)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+f}),a.onTrigger("Tracker:Plugin:Load:"+f,function(a,b){var f=a.split(":"),
d=f[3];"Ok"===f[4]&&(e.plugins[d]=!1,e.mcount--,0===e.mcount&&c())},!0),p(f))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&m(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=function(a){var h=this,g={},d=function(a){if(a.name){var c=!0;"undefined"!==typeof configuration&&(configuration.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(configuration.include,a.name)&&(c=!1),configuration.exclude instanceof Array&&
-1!==ATInternet.Utils.arrayIndexOf(configuration.exclude,a.name)&&(c=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var d={};d[a.name]={"function":ATInternet.Callbacks[a.name]};c&&h.load(a.name,d[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=d[a.name])}}};h.load=function(b,c){"function"===typeof c?(new c(a),a.emit("Tracker:Callback:Load:"+b+":Ok",{lvl:"INFO",details:{obj:c}})):a.emit("Tracker:Callback:Load:"+
b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:c}});return a};h.init=function(){if(a.getConfig("activateCallbacks")){var b=a.getConfig("callbacks");if("undefined"!==typeof b&&b.include instanceof Array)for(var c=0;c<b.include.length;c++)ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(b.include[c])&&(g[b.include[c]]={"function":ATInternet.Callbacks[b.include[c]]},ATInternet.Tracker.callbackProtos[b.include[c]]||(ATInternet.Tracker.callbackProtos[b.include[c]]=g[b.include[c]]));
else for(c in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(c)&&(g[c]={"function":ATInternet.Callbacks[c]},ATInternet.Tracker.callbackProtos[c]||(ATInternet.Tracker.callbackProtos[c]=g[c]));if("undefined"!==typeof b&&b.exclude instanceof Array)for(c=0;c<b.exclude.length;c++)g[b.exclude[c]]&&(g[b.exclude[c]]=void 0);for(var k in g)g.hasOwnProperty(k)&&g[k]&&h.load(k,g[k]["function"]);ATInternet.Utils.addCallbackEvent(d)}};h.removeCallbackEvent=function(){ATInternet.Utils.removeCallbackEvent(d)}},
BufferManager=function(a){var h=this,g={};h.set=function(a,b,e){e=e||{};e.hitType=e.hitType||["page"];g[a]={_value:b,_options:e}};var d=function(a,b,e){return(a=ATInternet.Utils.cloneSimpleObject(a[b]))&&!e?a._value:a},b=function k(a,b){if(!(a&&b instanceof Array&&a instanceof Array))return[];if(0===a.length)return b;var f=a[0],d,r=[],p=ATInternet.Utils.cloneSimpleObject(a);p.shift();for(var n=0;n<b.length;n++)if("object"!==typeof f[1])g[b[n]]&&g[b[n]]._options[f[0]]===f[1]&&r.push(b[n]);else{d=f[1].length;
for(var q=0;q<d;q++)if(g[b[n]]&&g[b[n]]._options[f[0]]instanceof Array&&0<=ATInternet.Utils.arrayIndexOf(g[b[n]]._options[f[0]],f[1][q])){r.push(b[n]);break}}return k(p,r)};h.get=function(a,e){var h={};if("string"===typeof a)h=d(g,a,e);else for(var f=b(a,ATInternet.Utils.getObjectKeys(g)),l=0;l<f.length;l++)h[f[l]]=d(g,f[l],e);return h};h.presentInFilters=function(a,b){return a&&0!==a.length?a[0][0]===b?!0:h.presentInFilters(a.slice(1),b):!1};h.addInFilters=function(a,b,d,f){if(!a||0===a.length)return f?
[]:[[b,d]];var l=a[0][0],r=a[0][1];l===b&&(r instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(r,d[0])&&r.push(d[0]),f=!0);return[[l,r]].concat(h.addInFilters(a.slice(1),b,d,f))};h.del=function(a){g[a]=void 0};h.clear=function(){g={}}},PropertiesManager=function(a){var h=this,g={};h.setProp=function(a,b,c){"undefined"!==typeof a&&(g[a]={value:b,persistent:!!c})};h.setProps=function(a,b){if(ATInternet.Utils.isObject(a))for(var c in a)a.hasOwnProperty(c)&&h.setProp(c,a[c],b)};h.delProp=function(d,
b){"undefined"!==typeof g[d]&&delete g[d];!b&&a.delParam(d.toLowerCase())};h.delProps=function(a){for(var b in g)g.hasOwnProperty(b)&&h.delProp(b,a)};h.getProp=function(a){g=g||{};return g[a]};h.getProps=function(){return g}},Tag=function(a,h,g){h=h||{};var d=this;d.version="5.21.0";var b=ATInternet.Utils.cloneSimpleObject(h);d.triggers=new TriggersManager(d);d.emit=d.triggers.emit;d.onTrigger=d.triggers.on;var c=ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},k;for(k in a)a.hasOwnProperty(k)&&
(c[k]=a[k]);d.getConfig=function(a){return c[a]};d.setConfig=function(a,b,f){void 0!==c[a]&&f||(d.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:c[a],aft:b}}),c[a]=b)};d.configPlugin=function(a,b,f){c[a]=c[a]||{};for(var l in b)b.hasOwnProperty(l)&&void 0===c[a][l]&&(c[a][l]=b[l]);f&&(f(c[a]),d.onTrigger("Tracker:Config:Set:"+a,function(a,b){f(b.details.aft)}));return c[a]};d.getContext=function(a){return b[a]};d.setContext=function(a,c){d.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:b[a],
aft:c}});b[a]=c};d.delContext=function(a,c){d.emit("Tracker:Context:Deleted:"+a+":"+c,{lvl:"INFO",details:{key1:a,key2:c}});if(a)b.hasOwnProperty(a)&&(c?b[a]&&b[a].hasOwnProperty(c)&&(b[a][c]=void 0):b[a]=void 0);else if(c)for(var f in b)b.hasOwnProperty(f)&&b[f]&&b[f].hasOwnProperty(c)&&(b[f][c]=void 0)};d.plugins=new PluginsManager(d);d.buffer=new BufferManager(d);d.setParam=d.buffer.set;d.getParams=function(a){return d.buffer.get(a,!1)};d.getParam=d.buffer.get;d.delParam=d.buffer.del;d.builder=
new BuildManager(d);d.sendUrl=d.builder.sendUrl;d.callbacks=new CallbacksManager(d);d.properties=new PropertiesManager(d);d.setProp=d.properties.setProp;d.setProps=d.properties.setProps;d.delProp=d.properties.delProp;d.delProps=d.properties.delProps;d.getProp=d.properties.getProp;d.getProps=d.properties.getProps;d.sendHit=function(a,b,c,l){var k=d.getProps(),p,n;for(n in k)k.hasOwnProperty(n)&&(p=k[n].value,k[n].persistent?d.setParam(n.toLowerCase(),p,{permanent:!0,hitType:["all"],encode:!0}):(ATInternet.Utils.isObject(a)?
a[n.toLowerCase()]={_value:p,_options:{hitType:["all"],encode:!0}}:d.setParam(n.toLowerCase(),p,{hitType:["all"],encode:!0}),d.delProp(n,!0)));d.builder.send(a,b,c,l)};d.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});(d.getConfig("disableCookie")||d.getConfig("disableStorage"))&&d.setParam("idclient",ATInternet.Utils.privacy.CONSENTNO,{permanent:!0,hitType:["all"]});d.getConfig("medium")&&d.setParam("medium",d.getConfig("medium"),{permanent:!0,hitType:["all"]});
d.plugins.init();d.callbacks.init();d.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:d,args:{config:a,context:h,callback:g}}});g&&g(d);ATInternet.Tracker.instances.push(d)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,h){h=h||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=h;for(var g=0;g<ATInternet.Tracker.instances.length;g++)ATInternet.Tracker.instances[g].plugins.load(a,h)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var h=0;h<ATInternet.Tracker.instances.length;h++)ATInternet.Tracker.instances[h].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);(function(){var dfltPluginCfg={"lifetime":30,"lastPersistence":true,"listEventsForExec":[],"domainAttribution":true};var dfltGlobalCfg={"visitLifetime":30,"redirectionLifetime":30};ATInternet.Tracker.Plugins.Campaigns=function(a){a.setConfig("visitLifetime",dfltGlobalCfg.visitLifetime,!0);a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var h={},g,d;a.configPlugin("Campaigns",dfltPluginCfg||{},function(a){h=a});var b,c,k,e,m,f,l,r,p,n,q,v,s,u=function(){var b=function(a){var b="";a&&(b=isNaN(a)&&-1===a.search(/^\[(.*?)\]$/g)&&-1===a.search(/^\d+\[(.*?)\]$/g)?"["+a+"]":a);return b},c=function(a){var b=a;-1!==a.search(/[-]/g)&&-1===a.search(/^\[(.*?)\]$/g)&&
(b="["+a+"]");return b},f=function(a){for(;"-"===a.charAt(a.length-1);)a=a.substring(0,a.length-1);return a};this.SponsoredLinks=function(){var e={google:"goo",yahoo:"ysm",miva:"miv",orange:"wan",msn:"msn",mirago:"mir",sklik:"skl",adfox:"adf",etarget:"etg",yandex:"yan",ebay:"eba",searchalliance:"sal",bing:"bin",naver:"nav",baidu:"bdu",qwant:"qwt",waze:"waz",amazon:"amz"},d={search:"s",content:"c"};this.atMedium="sl";this.atTerm=this.atNetwork=this.atVariant=this.atCreation=this.atPlatform=this.atCampaign=
"";this.format=function(){var a="sec",k=b(this.atCampaign),l=e[this.atPlatform]||c(this.atPlatform),p=b(this.atCreation),n=b(this.atVariant),r=d[this.atNetwork]||c(this.atNetwork),q=b(this.atTerm);return f(a+("-"+k+"-"+l+"-"+p+"-"+n+"-"+r+"-"+q))};this.setProperties=function(b){this.atCampaign=a.utils.getQueryStringValue("at_campaign",b)||"";this.atPlatform=a.utils.getQueryStringValue("at_platform",b)||"";this.atCreation=a.utils.getQueryStringValue("at_creation",b)||"";this.atVariant=a.utils.getQueryStringValue("at_variant",
b)||"";this.atNetwork=a.utils.getQueryStringValue("at_network",b)||"";this.atTerm=a.utils.getQueryStringValue("at_term",b)||""}};this.Email=function(){var e={acquisition:"erec",retention:"epr",promotion:"es"};this.atMedium="email";this.atSendTime=this.atRecipientList=this.atRecipientId=this.atLink=this.atSendDate=this.atCreation=this.atCampaign=this.atEmailtype="";this.format=function(){var a=e[this.atEmailtype]||e.promotion,d=b(this.atCampaign),k=b(this.atCreation),l=c(this.atSendDate),p=b(this.atLink),
n=c(this.atRecipientId)+(this.atRecipientList?"@"+c(this.atRecipientList):""),r=c(this.atSendTime);return f(a+("-"+d+"-"+k+"-"+l+"-"+p+"-"+n+"-"+r))};this.setProperties=function(b){this.atEmailtype=a.utils.getQueryStringValue("at_emailtype",b)||"";this.atCampaign=a.utils.getQueryStringValue("at_campaign",b)||"";this.atCreation=a.utils.getQueryStringValue("at_creation",b)||"";this.atSendDate=a.utils.getQueryStringValue("at_send_date",b)||"";this.atLink=a.utils.getQueryStringValue("at_link",b)||"";
this.atRecipientId=a.utils.getQueryStringValue("at_recipient_id",b)||"";this.atRecipientList=a.utils.getQueryStringValue("at_recipient_list",b)||"";this.atSendTime=a.utils.getQueryStringValue("at_send_time",b)||""}};this.Affiliate=function(){this.atMedium="affiliate";this.atVariant=this.atCreation=this.atFormat=this.atIdentifier=this.atType=this.atCampaign="";this.format=function(){var a="al",c=b(this.atCampaign),e=b(this.atType),d=b(this.atIdentifier),k=b(this.atFormat),l=b(this.atCreation),p=b(this.atVariant);
return f(a+("-"+c+"-"+e+"-"+d+"-"+k+"-"+l+"-"+p))};this.setProperties=function(b){this.atCampaign=a.utils.getQueryStringValue("at_campaign",b)||"";this.atType=a.utils.getQueryStringValue("at_type",b)||"";this.atIdentifier=a.utils.getQueryStringValue("at_identifier",b)||"";this.atFormat=a.utils.getQueryStringValue("at_format",b)||"";this.atCreation=a.utils.getQueryStringValue("at_creation",b)||"";this.atVariant=a.utils.getQueryStringValue("at_variant",b)||""}};this.Display=function(){this.atMedium=
"display";this.atDetailPlacement=this.atGeneralPlacement=this.atChannel=this.atFormat=this.atVariant=this.atCreation=this.atCampaign="";this.format=function(){var a="ad",c=b(this.atCampaign),e=b(this.atCreation),d=b(this.atVariant),k=b(this.atFormat),l=b(this.atChannel),p=b(this.atGeneralPlacement),n=b(this.atDetailPlacement);return f(a+("-"+c+"-"+e+"-"+d+"-"+k+"-"+l+"-"+p+"-"+n))};this.setProperties=function(b){this.atCampaign=a.utils.getQueryStringValue("at_campaign",b)||"";this.atCreation=a.utils.getQueryStringValue("at_creation",
b)||"";this.atVariant=a.utils.getQueryStringValue("at_variant",b)||"";this.atFormat=a.utils.getQueryStringValue("at_format",b)||"";this.atChannel=a.utils.getQueryStringValue("at_channel",b)||"";this.atGeneralPlacement=a.utils.getQueryStringValue("at_general_placement",b)||"";this.atDetailPlacement=a.utils.getQueryStringValue("at_detail_placement",b)||""}};this.Custom=function(){this.atCustom4=this.atCustom3=this.atCustom2=this.atCustom1=this.atCampaign=this.atMedium="";this.format=function(){var a=
"";/\d+$/.test(this.atMedium)&&(a=/\d+$/.exec(this.atMedium)[0]);var a="cs"+a,c=b(this.atCampaign),e=b(this.atCustom1),d=b(this.atCustom2),k=b(this.atCustom3),l=b(this.atCustom4);return f(a+("-"+c+"-"+e+"-"+d+"-"+k+"-"+l))};this.setProperties=function(b){this.atMedium=a.utils.getQueryStringValue("at_medium",b)||"";this.atCampaign=a.utils.getQueryStringValue("at_campaign",b)||"";this.atCustom1=a.utils.getQueryStringValue("at_custom1",b)||"";this.atCustom2=a.utils.getQueryStringValue("at_custom2",b)||
"";this.atCustom3=a.utils.getQueryStringValue("at_custom3",b)||"";this.atCustom4=a.utils.getQueryStringValue("at_custom4",b)||""}};this.medium={sl:this.SponsoredLinks,email:this.Email,affiliate:this.Affiliate,display:this.Display}},y=function(b,c){var f=a.storage[d](b);if(null!==f)return"object"===typeof f&&!(f instanceof Array);a.storage[g](b,{},c);return!0},w=function(b,c){var f=a.getContext("campaigns")||{};f[b]=c;a.setContext("campaigns",f)};(function(){a.plugins.waitForDependencies(["Storage",
"Utils"],function(){g="set"+(h.domainAttribution?"":"Private");d="get"+(h.domainAttribution?"":"Private");b=a.storage[d](["atredir","gopc"]);c=a.storage[d](["atredir","gopc_err"]);k=a.storage[d](["atredir","camp"]);a.storage.del(["atredir","gopc"]);a.storage.del(["atredir","gopc_err"]);a.storage.del(["atredir","camp"]);e=a.storage[d](["atsession","histo_camp"]);m=a.storage[d](["atreman","camp"]);f=a.storage[d](["atreman","date"]);var t=a.utils.getLocation(),z=a.utils.getQueryStringValue("at_medium",
t);if(z){var B=new u,z="function"===typeof B.medium[z]?new B.medium[z]:new B.Custom;z.setProperties(t);l=z.format()}else l=a.utils.getQueryStringValue("xtor",t);r=a.utils.getQueryStringValue("xtdt",t);p=a.utils.getQueryStringValue("xts",t);n=a.getContext("forcedCampaign");q=!!a.getConfig("redirect");v=!!(l&&r&&p);s=!1;v&&(t=(new Date).getTime()/6E4,s=!q&&p!==a.getConfig("site")||0>t-r||t-r>=a.getConfig("visitLifetime"));t=n||k||l;q&&t&&y("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&
(a.storage[g](["atredir","camp"],t),z=t=!1,n||(k?(t=b,z=c):(t=v,z=s)),a.storage[g](["atredir","gopc"],t),a.storage[g](["atredir","gopc_err"],z));!q&&m&&(w("xtor",m),t=(new Date).getTime()/36E5,t=Math.floor(t-f),w("roinbh",0<=t?t:0));q||(t=null,t=k?b?n||t:n||k:v?n:n||l||t,e&&e instanceof Array&&-1<e.indexOf(t)&&(t=null),t&&w("xto",t));if(!q&&!n){var A;k?c&&(A=k):s&&(A=l);A&&w("pgt",A)}if(!q&&(A=k?n||k:n||l||null)&&!(!n&&!k&&v&&s||!n&&k&&b&&c)){if((!e||e instanceof Array&&0>e.indexOf(A))&&y("atsession",
{path:"/",session:60*a.getConfig("visitLifetime")}))a.storage[g](["atsession","histo_camp"],e&&e.push(A)?e:[A]);m&&!h.lastPersistence||!y("atreman",{path:"/",session:86400*h.lifetime})||(a.storage[g](["atreman","camp"],A),a.storage[g](["atreman","date"],(new Date).getTime()/36E5))}a.emit("Campaigns:process:done",{lvl:"INFO"})})})()};ATInternet.Tracker.addPlugin("Campaigns");
}).call(window);(function(){var dfltPluginCfg={};var dfltGlobalCfg={"storageMode":"cookie"};ATInternet.Tracker.Plugins.Cookies=ATInternet.Tracker.Plugins.Storage=function(a){var h=this,g={},d=!1,b=null;a.configPlugin("Storage",dfltPluginCfg||{},function(a){g=a;"localStorage"===g.storageMode&&(d=ATInternet.Utils.isLocalStorageAvailable())});var c={},k=function(b){return a.getConfig("base64Storage")?ATInternet.Utils.Base64.encode(b):encodeURIComponent(b)},e=function(b){return a.getConfig("base64Storage")?ATInternet.Utils.Base64.decode(b):decodeURIComponent(b)},m=function(){this.getData=function(a){var b=
null;(a=RegExp("(?:^| )"+a+"=([^;]+)").exec(document.cookie)||null)&&(b=e(a[1]));return b};this.setData=function(b){var c=!1;if(b.name&&"string"===typeof b.name){var d=b.options||{},e=d.end||{},f=d.domain||a.getConfig("cookieDomain"),g=d.secure||a.getConfig("cookieSecure"),h=ATInternet.Utils.jsonSerialize(b),h=b.name+"="+k(h),h=h+(d.path&&"string"===typeof d.path?";path="+d.path:""),h=h+(f&&"string"===typeof f?";domain="+f:"")+(g&&"boolean"===typeof g?";secure":"");"function"===typeof e.toUTCString?
h+=";expires="+e.toUTCString():"number"===typeof e&&(h+=";max-age="+e.toString());document.cookie=h;this.getData(b.name)&&(c=!0)}return c}};b=d?new function(){var a=function(a){var b=+new Date,c=!1,d;a.options&&("undefined"!==typeof a.options.expires?d=a.options.expires:(a=a.options.end||{},"function"===typeof a.getTime?d=a.getTime():"number"===typeof a&&(d=b+1E3*a)));"number"===typeof d&&b>=d&&(c=!0);return{itemToDelete:c,timestamp:d}},b=function(a){var b=!1;try{localStorage.removeItem(a),b=!0}catch(c){}return b};
this.getData=function(c){var d=null,f=localStorage.getItem(c);if(f){var f=e(f),k=ATInternet.Utils.jsonParse(f);k&&"object"===typeof k?a(k).itemToDelete&&b(c)||(delete k.options.expires,d=ATInternet.Utils.jsonSerialize(k)):d=f}return d};this.setData=function(c){var d=!1;if(c.name&&"string"===typeof c.name){var e=a(c);"number"===typeof e.timestamp&&(c.options.expires=e.timestamp);var f=ATInternet.Utils.jsonSerialize(c);if(e.itemToDelete)d=b(c.name);else try{localStorage.setItem(c.name,k(f)),d=!0}catch(g){}}return d}}:
new m;var f=function(c,d){var e=!1;c&&"object"===typeof c&&(d||ATInternet.Utils.consent&&!a.getConfig("disableCookie")&&!a.getConfig("disableStorage"))&&(e=b.setData(c));return e},l=function(a,b,c){a={name:a,val:b};c&&c.session&&"number"===typeof c.session&&(c.end=c.session);a.options=c||{};return a},r=function(c){var d=null,e=null;a.getConfig("disableCookie")||a.getConfig("disableStorage")||!c||"string"!==typeof c||(e=b.getData(c));(c=e)&&(d=ATInternet.Utils.jsonParse(c));return d},p=function(a,
b){var c=ATInternet.Utils.cloneSimpleObject(a);return f(c,b)?ATInternet.Utils.jsonParse(ATInternet.Utils.jsonSerialize(a)):null},n=function(a,b,d){if(!d&&c[a])d=c[a];else if(d=r(a))d.options=d.options||{},d.options.session&&"number"===typeof d.options.session&&(d.options.end=d.options.session,p(d,!1)),c[a]=d;return d?b?(a=null,!d||"object"!==typeof d.val||d.val instanceof Array||void 0===d.val[b]||(a=d.val[b]),a):d.val:null},q=function(a,b,d,e,f){if(b){if(f=r(a))!f||"object"!==typeof f.val||f.val instanceof
Array?f=null:"undefined"===typeof d?delete f.val[b]:f.val[b]=d,f&&(f=p(f,e))}else f=f||{},f=l(a,d,f),f=p(f,e);return f?(c[a]=f,f.val):null},v=function(a,b){if(b)q(a,b,void 0,!0,null);else{c[a]=void 0;var d=l(a,"",{end:new Date("Thu, 01 Jan 1970 00:00:00 UTC"),path:"/"});f(d,!0)}};a.storage={};a.storage.get=h.get=function(a,b){b=!!b;return a instanceof Array?n(a[0],a[1],b):n(a,"",b)};a.storage.getPrivate=h.getPrivate=function(b,c){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");
return h.get(b,c)};a.storage.set=h.set=function(a,b,c,d){var e;a instanceof Array?(e=a[0],a=a[1],c=null):(e=a,a=null);return q(e,a,b,d,c)};a.storage.setPrivate=h.setPrivate=function(b,c,d){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return h.set(b,c,d)};a.storage.del=h.del=function(a){a instanceof Array?v(a[0],a[1]):v(a,"")};a.storage.delPrivate=h.delPrivate=function(b){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");h.del(b)};a.storage.cacheInvalidation=
h.cacheInvalidation=function(){c={}}};ATInternet.Tracker.addPlugin("Storage");ATInternet.Tracker.addPlugin("Cookies");
}).call(window);(function(){var dfltPluginCfg={};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.Utils=function(a){var h=this,g={};a.utils={};a.utils.getQueryStringValue=h.getQueryStringValue=function(a,c){var d=ATInternet.Utils.hashcode(c).toString();if(!g[d]){g[d]={};for(var e=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),h=e.exec(c);null!==h;)g[d][h[1]]=h[2],h=e.exec(c)}return g[d].hasOwnProperty(a)?g[d][a]:null};a.utils.manageChapters=h.manageChapters=function(b,c,d){var e="";if(b)for(var g=a.getConfig("ignoreEmptyChapterValue"),f="",h=1;h<parseInt(d,10)+1;h++)f=b[c+
h]||"",e=g?e+(f?f+"::":""):e+(b.hasOwnProperty(c+h)?f+"::":"");return e};a.utils.getDocumentLevel=h.getDocumentLevel=function(){var b=a.getConfig("documentLevel");if(b){if(0>b.indexOf("."))return window[b]||document;b=b.split(".");return window[b[0]][b[1]]||document}return document};a.utils.getLocation=h.getLocation=function(){return h.getDocumentLevel().location.href};a.utils.getHostName=h.getHostName=function(){return h.getDocumentLevel().location.hostname};a.dispatchIndex={};a.dispatchStack=[];
a.dispatchEventFor={};var d=0;a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.addSpecificDispatchEventFor=function(b){return a.dispatchEventFor[b]?!1:(a.dispatchEventFor[b]=!0,d++,!0)};a.processSpecificDispatchEventFor=function(b){a.dispatchEventFor[b]&&(a.dispatchEventFor[b]=!1,d--,0===d&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};
a.dispatch=function(b){var c=function(){for(var c="",d=null;0<a.dispatchStack.length;)c=a.dispatchStack.pop(),0===a.dispatchStack.length&&(d=b),a[c].onDispatch(d);a.dispatchIndex={};a.delContext(void 0,"customObject")},k=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){c()},!0);else c()};if(0===d)k();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){k()},!0)};a.dispatchRedirect=function(b){var c=!0,d=null;b&&(d=
null,b.hasOwnProperty("event")&&(d=b.event||window.event),!ATInternet.Utils.isTabOpeningAction(d)&&b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem,d],function(a){c=a})),d=b.callback);a.dispatch(d);return c};a.manageSend=function(b){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){b(a)})||b()};a.processTagObject=function(b,c,d){if((b=a.getParam(b,!0))&&b._options.permanent){for(var e=!1,g=b._options.hitType||[],f=0;f<
g.length;f++)if(-1!==ATInternet.Utils.arrayIndexOf(c.concat("all"),g[f])){e=!0;break}e&&(d=ATInternet.Utils.completeFstLevelObj(b._value||{},d,!0))}return d};a.processContextObjectAndSendHit=function(b,c,d,e){var g={hitType:c.hitType,encode:c.encode,separator:c.separator,truncate:c.truncate},f=a.getParam(b,!0);if(f){for(var h=!1,r=f._options.hitType||[],p=0;p<r.length;p++)if(-1!==ATInternet.Utils.arrayIndexOf(c.hitType.concat("all"),r[p])){h=!0;break}h?(h=ATInternet.Utils.cloneSimpleObject(f),h._value=
ATInternet.Utils.completeFstLevelObj(h._value||{},d,!0),a.setParam(b,h._value,g),a.manageSend(function(){a.sendHit(null,[["hitType",c.hitType]],e,c.requestMethod)}),f._options.permanent&&a.setParam(b,f._value,f._options)):(a.setParam(b,d,g),a.manageSend(function(){a.sendHit(null,[["hitType",c.hitType]],e,c.requestMethod)}),a.setParam(b,f._value,f._options))}else a.setParam(b,d,g),a.manageSend(function(){a.sendHit(null,[["hitType",c.hitType]],e,c.requestMethod)})}};ATInternet.Tracker.addPlugin("Utils");
}).call(window);(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.TechClicks=function(a){var h=this,g=["Tracker:Hit:Sent:Ok","Tracker:Hit:Sent:Error","Tracker:Hit:Sent:NoTrack"],d,b;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){d=a.clicksAutoManagementEnabled;b=a.clicksAutoManagementTimeout});var c=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},k=function(a){a.mailto?h.timeout=setTimeout(function(){window.location.href=
a.mailto},a.timeout):a.form?h.timeout=setTimeout(function(){a.form.submit()},a.timeout):a.url&&(h.timeout=setTimeout(function(){c({url:a.url,target:a.target})},a.timeout))},e=function(b){for(var c=0;c<g.length;c++)a.onTrigger(g[c],function(a,c){h.timeout&&clearTimeout(h.timeout);b&&b(c)})},m=function(a){for(var d,f="_self",g=a.timeoutonly;a;){if(a.href&&0===a.href.indexOf("http")){d=a.href.split('"').join('\\"');f=a.target?a.target:f;break}a=a.parentNode}d&&(g||e(function(a){!a.details.isMultiHit&&
c({url:d,target:f})}),k({url:d,target:f,timeout:b}))},f=function(a){var c=a;for(a=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;c&&(a||e(function(a){!a.details.isMultiHit&&c.submit()}),k({form:c,timeout:b}))},l=function(a){var c=a;for(a=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;c&&(a||e(function(a){a.details.isMultiHit||(window.location.href=c.href)}),k({mailto:c.href,timeout:b}))},r=function(a){for(var b=a;b;){if(b.href){if(0<=b.href.indexOf("mailto:"))return"mailto";
if(0===b.href.indexOf("http"))return"redirection"}else if("FORM"===b.nodeName){var c=a;a=!1;c&&(b=c.tagName||"",b=b.toLowerCase(),"form"===b?a=!0:(c=c.getAttribute("type")||"",c=c.toLowerCase(),"button"===b?"reset"!==c&&"button"!==c&&(a=!0):"input"===b&&"submit"===c&&(a=!0)));if(a)return"form";break}b=b.parentNode}return""};a.techClicks={};a.techClicks.manageClick=h.manageClick=function(a,b){var c=!0;if(d&&a){var e;a:{for(e=a;e;){if("function"===typeof e.getAttribute&&("_blank"===e.getAttribute("target")||
"no"===e.getAttribute("data-atclickmanagement"))){e=!0;break a}e=e.parentNode}e=a;for(var k=window.location.href,g;e;){if((g=e.href)&&0<=g.indexOf("#")&&k.substring(0,0<=k.indexOf("#")?k.indexOf("#"):k.length)===g.substring(0,g.indexOf("#"))){e=!0;break a}e=e.parentNode}e=!1}k=r(a);if(!e&&k){switch(k){case "mailto":l(a);c=!1;break;case "form":f(a);c=!1;break;case "redirection":m(a),c=!1}b&&(e=b.defaultPrevented,"function"===typeof b.isDefaultPrevented&&(e=b.isDefaultPrevented()),e||b.preventDefault&&
b.preventDefault())}}return c};a.techClicks.deactivateAutoManagement=function(){d=!1}};ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);(function(){var dfltPluginCfg={"requestMethod":"POST"};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.Clicks=function(a){var h={};a.configPlugin("Clicks",dfltPluginCfg||{},function(a){h=a});var g=function(a){var b="";switch(a){case "exit":b="S";break;case "download":b="T";break;case "action":b="A";break;case "navigation":b="N"}return b},d=function(b){return a.utils.manageChapters(b,"chapter",3)+(b.name?b.name:"")},b=function(b){var k={p:d(b),s2:b.level2||"",click:g(b.type)||""},e=["click"],m=a.getContext("page")||{};k.pclick=d(m);k.s2click=m.level2||"";if(m=b.customObject)m=
a.processTagObject("stc",e,m),k.stc={_value:ATInternet.Utils.jsonSerialize(m),_options:{hitType:e,encode:!0,separator:",",truncate:!0}};a.sendHit(k,[["hitType",e]],b.callback,h.requestMethod)};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(c){var d=!0,e=null;c&&c.hasOwnProperty("event")&&(e=c.event||window.event);!c.elem||"POST"===h.requestMethod&&ATInternet.Utils.isBeaconMethodAvailable()||ATInternet.Utils.isTabOpeningAction(e)||(d=a.techClicks.manageClick(c.elem,
e));b(c);return d};a.clickListener.send=this.clickListener.send=function(c){if(c.elem){var d="click";a.plugins.exec("TechClicks","isFormSubmit",[c.elem],function(a){d=a?"submit":"click"});ATInternet.Utils.addEvtListener(c.elem,d,function(e){"POST"===h.requestMethod&&ATInternet.Utils.isBeaconMethodAvailable()||ATInternet.Utils.isTabOpeningAction(e)||a.techClicks.manageClick(c.elem,e);b(c)})}};a.click.set=this.set=function(b){a.dispatchSubscribe("click");a.setContext("click",{name:d(b),level2:b.level2||
"",customObject:b.customObject});a.setParam("click",g(b.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(b){var k=["click"],e=a.getContext("click")||{},g=a.getContext("page")||{};a.setParam("pclick",d(g),{hitType:k});a.setParam("s2click",g.level2||"",{hitType:k});a.setParam("p",e.name,{hitType:k});a.setParam("s2",e.level2,{hitType:k});(e=e.customObject)?a.processContextObjectAndSendHit("stc",{hitType:k,encode:!0,separator:",",truncate:!0,requestMethod:h.requestMethod},e,
b):a.manageSend(function(){a.sendHit(null,[["hitType",k]],b,h.requestMethod)});a.setContext("click",void 0)}};ATInternet.Tracker.addPlugin("Clicks");
}).call(window);(function(){var dfltPluginCfg={"clientSideMode":"always","userIdCookieDuration":397,"userIdExpirationMode":"relative","optOut":"OPT-OUT","userIdStorageName":"atuserid","userIdHitName":"idclient","itpCompliant":false,"baseDomain":""};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var h={},g=!1,d=!1,b=null,c=-1;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){h=a});var k=function(){var b=h.baseDomain;if(!b){var c=a.getConfig("cookieDomain");c&&(b=c,"."===b.charAt(0)&&(b=b.substring(1,b.length)))}var c=a.builder.getCollectDomain(),f=a.utils.getHostName();return!!(b&&c&&f&&-1!==c.indexOf(b)&&-1!==f.indexOf(b))},e=function(){b={contextUserId:void 0,storageUserId:null,finalUserId:null,isFromTrackerContext:!1,
forceStorage:!1,optout:{isOptedout:!1,fromStorage:!1}}},m=function(){if("relative"===h.userIdExpirationMode||"fixed"===h.userIdExpirationMode&&null===b.storageUserId||b.isFromTrackerContext){var c=new Date;c.setTime(c.getTime()+864E5*h.userIdCookieDuration);a.storage.set(h.userIdStorageName,b.finalUserId,{end:c,path:"/"},b.forceStorage);ATInternet.Utils.consent&&!b.isFromTrackerContext&&b.finalUserId!==a.storage.get(h.userIdStorageName,!0)&&a.setParam(h.userIdHitName,b.finalUserId+"-NO",{multihit:!0,
permanent:!0,hitType:["all"]})}},f=function(){a.setParam(h.userIdHitName,b.finalUserId,{multihit:!0,permanent:!0,hitType:["all"]});m()},l=function(){e();var c=!1;null===ATInternet.Utils.optedOut?a.storage.get(h.userIdStorageName,!0)===h.optOut?c=ATInternet.Utils.optedOut=!0:ATInternet.Utils.optedOut=!1:!1===ATInternet.Utils.optedOut&&(a.getParam(h.userIdHitName)===h.optOut&&a.delParam(h.userIdHitName),a.storage.get(h.userIdStorageName,!0)===h.optOut&&a.storage.del(h.userIdStorageName));b.optout.isOptedout=
ATInternet.Utils.optedOut;b.optout.fromStorage=c;b.contextUserId=a.getContext("userIdentifier");b.storageUserId=a.storage.get("atuserid",!0);c=!1;if("required"===h.clientSideMode){var l="";window.navigator&&(l=window.navigator.userAgent);if(/Safari/.test(l)&&!/Chrome/.test(l)||/iPhone|iPod|iPad/.test(l))c=!0}else"always"===h.clientSideMode&&(c=!0);d=c;c=!1;if(!a.getConfig("forceHttp")&&h.itpCompliant&&"undefined"===typeof b.contextUserId&&!b.optout.isOptedout)switch(h.clientSideMode){case "never":c=
k();break;case "always":case "required":d&&null!==b.storageUserId||(c=k())}(g=c)||!d&&!b.optout.isOptedout&&"undefined"===typeof b.contextUserId?a.setConfig("userIdOrigin","server"):(a.setConfig("userIdOrigin","client"),b.isFromTrackerContext=!1,b.forceStorage=!1,b.optout.isOptedout?(b.finalUserId=h.optOut,b.isFromTrackerContext=!b.optout.fromStorage,b.forceStorage=!0):a.getConfig("disableCookie")||a.getConfig("disableStorage")?(b.finalUserId=a.getParam(h.userIdHitName),b.isFromTrackerContext=!0):
"undefined"!==typeof b.contextUserId?(b.finalUserId=b.contextUserId,b.isFromTrackerContext=!0):b.finalUserId=null!==b.storageUserId?b.storageUserId:ATInternet.Utils.uuid().v4(),f())},r=function(a){a&&(a=a.detail)&&"clientsideuserid"===a.name&&a.id===c&&l()};(function(){a.plugins.waitForDependencies(["Storage","Utils"],function(){var a=ATInternet.Utils.uuid();c=parseInt(a.num(8));ATInternet.Utils.removeOptOutEvent(r);ATInternet.Utils.addOptOutEvent(c,r);l()})})();a.clientSideUserId={};a.clientSideUserId.set=
function(a){b.optout.isOptedout||(b.finalUserId=a,b.isFromTrackerContext=!0,b.forceStorage=!1,f())};a.clientSideUserId.store=function(){b.finalUserId=a.getParam(h.userIdHitName)||b.finalUserId;null!==b.finalUserId&&b.finalUserId!==ATInternet.Utils.privacy.CONSENTNO&&b.finalUserId!==b.storageUserId&&(b.isFromTrackerContext=!0,b.forceStorage=!0,m())};a.clientSideUserId.get=function(){b.finalUserId=a.getParam(h.userIdHitName)||b.finalUserId;return b.finalUserId};a.clientSideUserId.clear=function(){e();
a.delParam(h.userIdHitName);a.storage.del(h.userIdStorageName)}};ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);(function(){var dfltPluginCfg={"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};ATInternet.Tracker.Plugins.ContextVariables=function(a){var h="",g=null,d,b="",c="",k={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){k=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var e=function(b,c){var f=null;a.plugins.exec("Storage",b,c,function(a){f=a});return f},m=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})},f=function(a){(a=d?d:"acc_dir"===h?
"":null!==h?h:"acc_dir"===g?"":g?g:a?a.referrer:"")&&(a=a.replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$"));return a};a.plugins.waitForDependencies(["Storage","Utils"],function(){b="set"+(k.domainAttribution?"":"Private");c="get"+(k.domainAttribution?"":"Private");var l=a.utils.getLocation();h=a.utils.getQueryStringValue("xtref",l);void 0===h&&(h="");d=a.getContext("forcedReferer");if(a.getConfig("redirect")){var l=a.utils.getDocumentLevel(),l=d?d:null!==h?h:l?l.referrer:"acc_dir",r;if(r=l){r=
{path:"/",end:a.getConfig("redirectionLifetime")};var p=e(c,["atredir"]);null!==p?r="object"===typeof p&&!(p instanceof Array):(e(b,["atredir",{},r]),r=!0)}r&&e(b,[["atredir","ref"],l])}else{g=e(c,[["atredir","ref"]]);e("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});l="";try{l+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+"x"+window.screen.colorDepth}catch(n){}a.setParam("r",
l,{permanent:!0,hitType:["all"]});l="";window.innerWidth?l+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(l+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",l,{permanent:!0,hitType:["all"]});m();window.navigator&&a.setParam("lng",window.navigator.language||window.navigator.userLanguage,{permanent:!0,hitType:["all"]});l=ATInternet.Utils.uuid().num(13);a.setParam("idp",l,{permanent:!0,hitType:["page","clickzone"]});window.navigator&&a.setParam("jv",
window.navigator.javaEnabled()?"1":"0",{hitType:["page"]});l=a.utils.getDocumentLevel();a.setParam("ref",f(l),{permanent:!0,last:!0,hitType:["page","ecommerce","avinsights"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);(function(){var dfltPluginCfg={};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.Page=function(a){var h=["pageId","chapterLabel","update"],g=["pid","pchap","pidt"],d=["page","site"],b=["f","x"],c=function(b){return a.utils.manageChapters(b,"chapter",3)+(b.name?b.name:"")},k=function(a,b,c){b?a=b:a||"undefined"===typeof c||(a=c);return a},e=function(a,b,c){b.hasOwnProperty(c)&&(a[c]=k(a[c],b[c]))},m=function(c,f,e){if(f)for(var k=0;k<d.length;k++)if(f.hasOwnProperty(d[k])&&f[d[k]])for(var g in f[d[k]])f[d[k]].hasOwnProperty(g)&&(e?c[b[k]+g]=f[d[k]][g]:
a.setParam(b[k]+g,f[d[k]][g]))},f=function(b,c,d){if(c){var f=a.utils.manageChapters(c,"chapter",3);f&&(c.chapterLabel=f.replace(/::$/gi,""));for(f=0;f<g.length;f++)c.hasOwnProperty(h[f])&&(d?b[g[f]]=c[h[f]]:a.setParam(g[f],c[h[f]]))}},l=function(b,c,d){if(c&&c.keywords instanceof Array){var f=c.keywords.length;if(0<f){for(var e="",k=0;k<f;k++)e+="["+c.keywords[k]+"]"+(k<f-1?"|":"");d?b.tag=e:a.setParam("tag",e)}}},r=function(b,c,d){if(c){var f,e=function(a){return a?a:"0"};f=""+(e(c.category1)+"-");
f+=e(c.category2)+"-";f+=e(c.category3);d?b.ptype=f:a.setParam("ptype",f)}},p=function(b,c,d){if(c)for(var f in c)c.hasOwnProperty(f)&&"undefined"!==typeof c[f]&&(d?b[f]=c[f]:a.setParam(f,c[f]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(b){var c=a.getContext("page")||{},d=c.customVars;if(d){if(b)for(var f in b)b.hasOwnProperty(f)&&(d[f]=ATInternet.Utils.completeFstLevelObj(d[f],b[f],!0))}else d=b;c.customVars=d;a.setContext("page",c)};a.dynamicLabel=this.dynamicLabel=
{};a.dynamicLabel.set=this.dynamicLabel.set=function(b){var c=a.getContext("page")||{};c.dynamicLabel=ATInternet.Utils.completeFstLevelObj(c.dynamicLabel,b,!0);a.setContext("page",c)};a.tags=this.tags={};a.tags.set=this.tags.set=function(b){var c=a.getContext("page")||{};c.tags=ATInternet.Utils.completeFstLevelObj(c.tags,b,!0);a.setContext("page",c)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(b){var c=a.getContext("page")||{};
c.customTreeStructure=ATInternet.Utils.completeFstLevelObj(c.customTreeStructure,b,!0);a.setContext("page",c)};a.page={};a.page.reset=this.reset=function(){a.delContext("page")};a.page.set=this.set=function(b){a.dispatchSubscribe("page");var c=a.getContext("page")||{};c.name=k(c.name,b.name,"");c.level2=k(c.level2,b.level2,"");e(c,b,"chapter1");e(c,b,"chapter2");e(c,b,"chapter3");c.customObject=ATInternet.Utils.completeFstLevelObj(c.customObject,b.customObject,!0);a.setContext("page",c)};a.page.send=
this.send=function(b){var d=!0,g={p:c(b),s2:b.level2||""},h=b.customObject;if(h){var u=["page"],h=a.processTagObject("stc",u,h);g.stc={_value:ATInternet.Utils.jsonSerialize(h),_options:{hitType:u,encode:!0,separator:",",truncate:!0}}}h=a.getContext("page")||{};h.vrn&&(g.vrn=h.vrn,a.delContext("page","vrn"));u=a.getContext("InternalSearch")||{};"undefined"!==typeof u.keyword&&(g.mc=ATInternet.Utils.cloneSimpleObject(u.keyword),"undefined"!==typeof u.resultPageNumber&&(g.np=ATInternet.Utils.cloneSimpleObject(u.resultPageNumber)),
a.delContext("InternalSearch"));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(g.pvw=1);m(g,b.customVars,!0);f(g,b.dynamicLabel,!0);l(g,b.tags,!0);r(g,b.customTreeStructure,!0);u=a.getContext("campaigns")||{};p(g,u,!0);a.delContext("campaigns");u=null;b&&b.hasOwnProperty("event")&&(u=b.event||window.event);!ATInternet.Utils.isTabOpeningAction(u)&&b.elem&&(d=a.techClicks.manageClick(b.elem,u));a.manageSend(function(){a.sendHit(g,null,b.callback,null)});h.name=k(h.name,b.name,"");h.level2=k(h.level2,
b.level2,"");e(h,b,"chapter1");e(h,b,"chapter2");e(h,b,"chapter3");a.setContext("page",h);return d};a.page.onDispatch=this.onDispatch=function(b){var d=a.getContext("page")||{},e=a.getContext("InternalSearch")||{};a.setParam("p",c(d));a.setParam("s2",d.level2||"");d.vrn&&(a.setParam("vrn",d.vrn),a.delContext("page","vrn"));"undefined"!==typeof e.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(e.keyword)),"undefined"!==typeof e.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(e.resultPageNumber)),
a.delContext("InternalSearch"));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);m(null,d.customVars,!1);f(null,d.dynamicLabel,!1);l(null,d.tags,!1);r(null,d.customTreeStructure,!1);e=a.getContext("campaigns")||{};p(null,e,!1);a.delContext("campaigns");var k=["page"];(d=d.customObject)?a.processContextObjectAndSendHit("stc",{hitType:k,encode:!0,separator:",",truncate:!0},d,b):a.manageSend(function(){a.sendHit(null,[["hitType",k]],b,null)})}};ATInternet.Tracker.addPlugin("Page");
}).call(window);(function(){var dfltPluginCfg={"lifetime":182,"domainAttribution":true};var dfltGlobalCfg={"redirectionLifetime":30};ATInternet.Tracker.Plugins.IdentifiedVisitor=function(a){var h=null,g=null,d=null,b=null,c="",k="",e=null,m=null,f="",l="",r="",p={};a.configPlugin("IdentifiedVisitor",dfltPluginCfg||{},function(a){p=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var n=function(b,c){var f=null;a.plugins.exec("Storage",b,c,function(a){f=a});return f},q=function(a,b){var c=n(l,[a,!0]);if(null!==c)return"object"===typeof c&&!(c instanceof Array);n(f,[a,{},b]);return!0},v=function(a,b){q("atidvisitor",
{path:"/",session:86400*p.lifetime})&&n(f,[["atidvisitor",a],b])},s=function(b,c,f){a.setParam(b,c,{hitType:["all"],permanent:!0});f&&v(b,c)},u=function(){var a=function(a,b){/-/.test(b)?(a.category=b.split("-")[0],a.id=b.split("-")[1]):a.id=b},b={category:"",id:""};a(b,k||m);var f={category:"",id:""};a(f,c||e);f.id?(f.category&&s("ac",f.category,!0),s("at",f.id,!0)):h&&(s("at",h,!1),d&&s("ac",d,!1));b.id?(b.category&&s("ac",b.category,!0),s("an",b.id,!0)):g&&s("anc",d+"-"+g,!1)};a.plugins.waitForDependencies(["Storage",
"Utils"],function(){f=p.domainAttribution?"set":"setPrivate";l=p.domainAttribution?"get":"getPrivate";r=p.domainAttribution?"del":"delPrivate";var s=a.utils.getLocation();c=a.utils.getQueryStringValue("xtat",s);k=a.utils.getQueryStringValue("xtan",s);a.getConfig("redirect")?(c||k)&&q("atredir",{path:"/",end:a.getConfig("redirectionLifetime")})&&(k&&n(f,[["atredir","an"],k]),c&&n(f,[["atredir","at"],c])):(e=n(l,[["atredir","at"]]),m=n(l,[["atredir","an"]]),n(r,[["atredir","at"]]),n(r,[["atredir","an"]]),
h=n(l,[["atidvisitor","at"]]),g=n(l,[["atidvisitor","an"]]),d=n(l,[["atidvisitor","ac"]]),b=n(l,[["atidvisitor","vrn"]]),u(),s="-"+a.getConfig("site")+"-",RegExp(s).test(b)||(b=(b||"")+s,v("vrn",b),s=a.getContext("page")||{},s.vrn=1,a.setContext("page",s)));a.emit("IdentifiedVisitor:Ready",{lvl:"INFO",details:{storageRedirectTextual:e,storageRedirectNumeric:m,storageTextual:h,storageNumeric:g,storageCategory:d,storageVrn:b}})});a.identifiedVisitor={};a.identifiedVisitor.set=function(a){var b=a.id;
a=a.category;"number"===typeof b?s("an",b.toString(),!0):"string"===typeof b&&s("at",b,!0);"undefined"!==typeof a&&s("ac",a,!0)};a.identifiedVisitor.unset=function(){for(var b=["an","at","ac"],c=0;c<b.length;c++)n(r,[["atidvisitor",b[c]]]),a.delParam(b[c]);a.delParam("anc")}};ATInternet.Tracker.addPlugin("IdentifiedVisitor");
}).call(window);(function(){var dfltPluginCfg={"urlKeyword":"q","urlResultPageNumber":"","urlResultPosition":""};var dfltGlobalCfg={};ATInternet.Tracker.Plugins.InternalSearch=function(a){var h={};a.configPlugin("InternalSearch",dfltPluginCfg||{},function(a){h=a});a.internalSearch={};a.internalSearch.set=function(g){var d={},b=d;g.hasOwnProperty("keyword")&&(b.keyword=g.keyword);b=d;g.hasOwnProperty("resultPageNumber")&&(b.resultPageNumber=g.resultPageNumber);g=a.getContext("InternalSearch")||{};d=ATInternet.Utils.completeFstLevelObj(d,g);"undefined"===typeof d.resultPageNumber&&(d.resultPageNumber="1");a.setContext("InternalSearch",
d)};a.internalSearch.send=function(g){var d=!0,b=null;g&&g.hasOwnProperty("event")&&(b=g.event||window.event);!ATInternet.Utils.isTabOpeningAction(b)&&g.elem&&(d=a.techClicks.manageClick(g.elem,b));b={np:"undefined"!==typeof g.resultPageNumber?g.resultPageNumber:"1",click:"IS"};g.hasOwnProperty("keyword")&&(b.mc=g.keyword);g.hasOwnProperty("resultPosition")&&(b.mcrg=g.resultPosition);var c=a.getContext("page")||{};c.level2&&(b.s2=c.level2);a.sendHit(b,[["hitType",["InternalSearch"]]],g.callback,null);
return d};a.plugins.waitForDependencies(["Utils"],function(){var g;if(h.urlKeyword){var d=document.location.href;g={};var b=a.utils.getQueryStringValue(h.urlKeyword,d);b&&(g.keyword=b);h.urlResultPageNumber&&(b=a.utils.getQueryStringValue(h.urlResultPageNumber,d),g.resultPageNumber=b||"1")}g&&a.setContext("InternalSearch",g);a.emit("InternalSearch:Ready",{lvl:"INFO",details:{config:{urlKeyword:h.urlKeyword,urlResultPageNumber:h.urlResultPageNumber},url:d,data:g}})})};ATInternet.Tracker.addPlugin("InternalSearch");
}).call(window);(function(){var dfltPluginCfg={};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.OnSiteAds=function(a){var h="",g=function(b){return a.utils.manageChapters(b,"chapter",3)+(b.name?b.name:"")},d=function(a,b){return a[b]?a[b]:""},b=function(a,b){var c=d(a,b);if(c){var e=d(a,"prefix");if(c.campaignId){var e=e||"PUB",k=d(c,"campaignId"),g=d(c,"creation"),h=d(c,"variant"),s=d(c,"format"),m=d(c,"generalPlacement"),y=d(c,"detailedPlacement"),w=d(c,"advertiserId"),c=d(c,"url");return e+"-"+k+"-"+g+"-"+h+"-"+s+"-"+m+"-"+y+"-"+w+"-"+c}if(c.adId)return e=
e||"INT",k=d(c,"adId"),g=d(c,"format"),c=d(c,"productId"),e+"-"+k+"-"+g+"||"+c}return""},c=function(c){var d=["onSiteAdsImpression"],e={};e.ati={_value:b(c,"impression"),_options:{hitType:d,truncate:!0}};e.type="AT";ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(e.pvw=1);var k=c.customObject;k&&(k=a.processTagObject("stc",d,k),e.stc={_value:ATInternet.Utils.jsonSerialize(k),_options:{hitType:d,encode:!0,separator:",",truncate:!0}});a.manageSend(function(){a.sendHit(e,[["hitType",d]],c.callback,
null)})},k=function(b,c){var d=a.buffer.get("ati",!0)||{};d._value="string"===typeof d._value?[d._value]:d._value||[];d._options=d._options||{truncate:!0,hitType:[c,"page"]};d._value.push(b);a.buffer.set("ati",d._value,d._options)},e=function(c,d){c.click?a.setParam("atc",b(c,"click"),{truncate:!0,hitType:[d,"page"]}):c.impression&&a.setParam("ati",b(c,"impression"),{truncate:!0,hitType:[d,"page"]});if(c.customObject){a.setContext("onsiteads",{customObject:c.customObject});var e=a.getContext("page")||
{};e.customObject=ATInternet.Utils.completeFstLevelObj(e.customObject,c.customObject,!1);a.setContext("page",e)}a.dispatchSubscribe("onSiteAds")};a.selfPromotion=this.selfPromotion={};a.publisher=this.publisher={};a.publisher.set=this.publisher.set=function(a){e(a,"publisher")};a.selfPromotion.set=this.selfPromotion.set=function(a){e(a,"selfPromotion")};a.publisher.add=this.publisher.add=function(c){k(b(c,"impression"),"publisher");a.dispatchSubscribe("onSiteAds")};a.selfPromotion.add=this.selfPromotion.add=
function(c){k(b(c,"impression"),"selfPromotion");a.dispatchSubscribe("onSiteAds")};var m=this.advertEvent=function(d){var e=!0,k=null;d&&d.hasOwnProperty("event")&&(k=d.event||window.event);!ATInternet.Utils.isTabOpeningAction(k)&&d.elem&&(e=a.techClicks.manageClick(d.elem,k));if(d.click){var k=["onSiteAdsClick"],h=a.getContext("page")||{},n={};n.atc={_value:b(d,"click"),_options:{truncate:!0}};n.type="AT";n.patc=g(h);n.s2atc=h.level2||"";if(h=d.customObject)h=a.processTagObject("stc",k,h),n.stc=
{_value:ATInternet.Utils.jsonSerialize(h),_options:{hitType:k,encode:!0,separator:",",truncate:!0}};a.sendHit(n,[["hitType",k]],d.callback,null)}else d.impression&&c(d);return e};a.publisher.send=this.publisher.send=function(a){return m(a)};a.selfPromotion.send=this.selfPromotion.send=function(a){return m(a)};a.onSiteAds={};a.onSiteAds.onDispatch=this.onDispatch=function(b){if(!a.dispatchSubscribed("page")){a.setParam("type","AT",{hitType:["publisher","selfPromotion"]});var c=a.getContext("page")||
{};a.getParam("atc")&&(a.setParam("patc",g(c),{hitType:["publisher","selfPromotion"]}),a.setParam("s2atc",c.level2||"",{hitType:["publisher","selfPromotion"]}));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);var d=["publisher","selfPromotion"];(c=(a.getContext("onsiteads")||{}).customObject)?a.processContextObjectAndSendHit("stc",{hitType:d,encode:!0,separator:",",truncate:!0},c,b):a.manageSend(function(){a.sendHit(null,[["hitType",d]],b,null)})}};a.plugins.waitForDependencies(["Utils",
"TechClicks"],function(){h=document.location.href;var b=a.utils.getQueryStringValue("xtatc",h);b&&a.setParam("atc",b,{hitType:["publisher","selfPromotion","page"]});a.emit("OnSiteAds:Ready",{lvl:"INFO",details:{href:h}})})};window.ATInternet.Tracker.addPlugin("OnSiteAds");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}


